---
title: 'Project 1: Wrangling, Exploration'
author: "SDS322E"
date: ''
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pdf_document:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

# Data Wrangling, Exploration

## Sung Joon Roh, sr52225

### Introduction 

The two datasets I will be using are both NBA (National Basketball Associated) related, with one dataset providing the per-game stats for all players, and the other providing the "advanced" per-game stats for all players (data basketball geeks drool over). I have loved basketball ever since I could lay my hands on one, and have been following the NBA from the age of 4. I wanted to work with sports statistics as it is so prevalent in today's world of sports, and examine ways I can make for interesting pieces of data with the tools that we have learned throughout this semester. 

```{R}
# read your datasets in here, e.g., with read_csv()

library(tidyverse)
library("dplyr")

dataset1 <- read_csv("/stor/home/sr52225/project1/nba2021_per_game.csv") # Per-game stats
dataset2 <- read_csv("/stor/home/sr52225/project1/nba2021_advanced.csv") # Advanced Stats

head(dataset1)
head(dataset2)

# read_csv() also takes in URLs
#readxl::read_excel() # reading excel sheets

```

```{R}
dataset1 <- dataset1 %>% group_by(Player) %>% filter(!n()==3)
dataset2 <- dataset2 %>% group_by(Player) %>% filter(!n()==3)

```
I noticed that the dataset had multiple duplicate instances of players. Specifically, if a player was either traded or released, then consequently signed by another team, their names would show up three times (three rows). One row would represent their total stats for the season so far, the next row would represent their stats with their original team, and the last row would represent their stats with their new team. Because it would be difficult to run a structured analysis having a team called "TOT" for "Total", and how unrealistic it is, I decided to filter out these unlucky 8 players (number of players traded) from each dataset. 
    
### Joining/Merging

```{R}
# your joining code

# your joining code
joined_dataset <- left_join(dataset1, dataset2, by="Player")
head(joined_dataset)
joined_dataset1 <- joined_dataset %>% 
  select(-Pos.y, -Age.y, -Tm.y, -G.y, -MP.y) %>%
  rename(Pos=Pos.x, Age=Age.x, Tm=Tm.x, G=G.x, MP=MP.x)
joined_dataset1

# 1. Total observations/rows in each dataset
dataset1 %>% glimpse()
dataset2 %>% glimpse()

# 2. Unique IDs in each dataset
dataset1 %>% distinct(Player) %>% summarize(n()) %>% nrow()
dataset2 %>% distinct(Player) %>% summarize(n()) %>% nrow()

# 3. IDs that appear in one dataset but not the other (and which those are)
dataset1 %>% anti_join(dataset2, by="Player") %>% summarize(n()) 
dataset2 %>% anti_join(dataset1, by="Player") %>% summarize(n())

# 4. IDs the datasets have in common
dataset1 %>% inner_join(dataset2, by="Player") %>% summarize(n()) %>% nrow()
dataset2 %>% inner_join(dataset1, by="Player") %>% summarize(n()) %>% nrow()

```
Breaking this portion up by section (5), the first section prepares the data after the initial left_join() function is called. I did this because I noticed there were duplicates with the columns joined, specifically in a ".x" or ".y" form at the end of the column header. Thus, I manually dropped one set of these columns and renamed the other to its original column header name. As a result, the new joined_dataset1 had 473 rows of player stats, as opposed to the original 481, and joined columns from each dataset filtered by player. 

Breaking down section 2, I ran the glimpse() functions for both datasets to find the total number of observations/rows for each. There are 473 rows, 29 columns and 13717 total observations in dataset1 (stats per game), while there are 473 rows, 26 columns and 12298 total observations in dataset2  (advanced stats per game).

Section 3 finds the distinct Player IDs as Player is the primary ID, finds the count, and the number of rows the grab the exact number. For section 4, an anti-join is used to find IDs (Player) that appear in one dataset and not the other. Unsurprisingly, the value was zero for both attempts. Lastly, the inner_join() function was called to find the IDs that both datasets had in common, and nrow() was called at the end to grab the exact number. Unsurprisingly, the value came out to be all 473 players. 

###  Wrangling

```{R}
# your wrangling code  
# Chosen variables: Player, PTS, Pts_per36min, Tm, Age, FTA (Free Throw Attempts), PER

# mutate - generate a variable that is a function of at least one other variable (pts_per36min): 
joined_dataset1 <- joined_dataset1 %>% mutate(Pts_per36min=round((36/MP)*PTS,1))

# str_replace / regex (Make team lowercase)
joined_dataset1 %>% mutate(Tm = str_replace(Tm, ".+", tolower(Tm)))

# Amount of players per team
joined_dataset1 %>% group_by(Tm) %>% summarize(Players_per_team=n_distinct(Player))

# Top scorers in the league (Highest PTS value)
joined_dataset1 %>% group_by(Player) %>% 
  arrange(desc(PTS)) %>% select(PTS) 

# joined_dataset1 %>% slice_max(PTS, n=10) not working for some reason
# slice_min, slice_max not working 

# Top scorers in the league per 36 minutes (Highest Pts_per36min)
joined_dataset1 %>% group_by(Player) %>% 
  arrange(desc(Pts_per36min)) %>% select(Pts_per36min)

# Oldest/youngest Team in the league, age average
joined_dataset1 %>% group_by(Tm) %>% summarize(avg_age=mean(Age)) %>%
  arrange(desc(avg_age))
joined_dataset1 %>% group_by(Tm) %>% summarize(avg_age=mean(Age)) %>%
  arrange(+avg_age)

joined_dataset1 %>% group_by(Tm) %>% summarize(avg_age=mean(Age)) %>%
  summarize(max(avg_age))
joined_dataset1 %>% group_by(Tm) %>% summarize(avg_age=mean(Age)) %>%
  summarize(min(avg_age))

# Overall count for each age in the league (lowest, highest)
joined_dataset1 %>% group_by(Age) %>% summarize(count=n()) %>%
  arrange(+count)
joined_dataset1 %>% group_by(Age) %>% summarize(count=n()) %>%
  arrange(-count)

# Overall Sum/Mean/SD for FTA (Free Throw Attempts) for each team in the league
joined_dataset1 %>% group_by(Tm) %>% summarize(Total_FTA=sum(FTA)) %>% arrange(desc(Total_FTA))
joined_dataset1 %>% group_by(Tm) %>% summarize(avg_FTA=mean(FTA)) %>% arrange(desc(avg_FTA))
joined_dataset1 %>% group_by(Tm) %>% summarize(sd_FTA=sd(FTA)) %>% arrange(desc(sd_FTA))

# mutate with ifelse()
joined_dataset1 %>% mutate(Stage=ifelse(Age<33, "Prime", "Not Prime"))

# 1 function, use it inside summarize, group by two categorical variables. 
distinct_observations <- function(x) length(unique(x))
joined_dataset1 %>% group_by(Tm, Pos) %>% summarize(unique_age=distinct_observations(Age))

# Table of counts for all categorical variables # not knitting properly, works in pre-code
joined_dataset1 %>% group_by(Pos) %>% summarize(Count=n()) #%>% #gt() #%>%
  #tab_header(title= "Player Counts for Each Position (Pos)")
joined_dataset1 %>% group_by(Age) %>% summarize(Count=n()) #%>% #gt() #%>%
  #tab_header(title= "Player Counts for Each Age")
joined_dataset1 %>% group_by(Tm) %>% summarize(Count=n()) #%>% #gt() #%>%

```

I decided to focus on the variables PTS, Pts_per36min, Tm, Age, and FTA. First, with the mutate function, I generate a new variable called Pts_per36min, which is actually a well-known basketball statistic but I was surprised to not see it in neither datasets. I equated it to 36 divided by the amount of minutes they average, multiplied by the total amount of points they average. Afterwards, I round to the single decimal, as this is a common trend in the world of basketbal statistics. 

With the str_replace and regex, I replaced all characters that show up one time or more in the team column with their lowercase characters. As a result, all teams which originally showed up as all-caps city abbreviations, are now lowercase. 

Other cool features included using mutate() to create a new variable with an ifelse() statement that involved listing players and whether they were in their primes or not. I self-defined under 33 years of age as being in one's athletic prime. What I enjoyed doing was creating the function to find a count of all unique observations. I grouped by two categorical variables to Team and Position, to find the count of all unique ages by position within the respective teams. 

All other lines of code involved finding summary statistics like mean, sd, sum, min, max, and sorting them by descending or ascending to find the highest or lowest ranked players. 



